using Microsoft.Data.Sqlite;
using SwiftMT103ApiTask.Models;
using NLog;
using System.Data;

namespace SwiftMT103ApiTask.Repositories
{
    public class MT103Repository : IMT103Repository
    {

        private string _connectionString;

        public readonly Logger Logger = LogManager.GetCurrentClassLogger();


        public MT103Repository(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("Default")
            ?? throw new InvalidOperationException("Connection string 'Default' is missing.");
        }

        /// <summary>
        /// Returns a MT103Message by id (the PK), or null if no record with the given ID is found.
        /// </summary>
        /// <param name="id">The id of the MT103Message</param>
        /// <returns>MT103Message or null if does not exist</returns>
        public async Task<MT103Message> GetByIdAsync(long id)
        {
            using var connection = new SqliteConnection(_connectionString);
            await connection.OpenAsync();

            using var command = connection.CreateCommand();
            command.CommandText = @"SELECT * FROM MT103Messages WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            using var reader = await command.ExecuteReaderAsync();

            if (await reader.ReadAsync())
            {
                // There is a record with the given Id

                // Create a MT103Message object and map all fields
                MT103Message message = new MT103Message
                {
                    Id = reader.GetInt64(reader.GetOrdinal("Id")),
                    ReferenceNumber = reader["ReferenceNumber"]?.ToString(),
                    BankOperationCode = reader["BankOperationCode"]?.ToString(),
                    Currency = reader["Currency"]?.ToString(),
                    OrderingCustomer = reader["OrderingCustomer"]?.ToString(),
                    AccountWithInstitution = reader["AccountWithInstitution"]?.ToString(),
                    Recepient = reader["Recepient"]?.ToString(),
                    RemittanceInformation = reader["RemittanceInformation"]?.ToString(),
                    DetailsOfCharge = reader["DetailsOfCharge"]?.ToString(),
                };

                return message;
            }

            // No record with the given Id is found.
            Logger.Warn("No MT103Message found with the given ID.");
            return null;
        }

        /// <summary>
        /// Gets all MT103 message records from the database
        /// </summary>
        /// <returns>A list of MT103Message</returns>
        public async Task<List<MT103Message>> GetAllAsync()
        {
            // Pagination is stricly needed in a real project, but for simplicity I decided to keep it simple
            using var connection = new SqliteConnection(_connectionString);
            await connection.OpenAsync();

            List<MT103Message> messages = new List<MT103Message>();


            using var command = connection.CreateCommand();
            command.CommandText = @"SELECT * FROM MT103Messages;";

            // Read file content
            using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                // Map values to a MT103Message object
                var message = new MT103Message
                {
                    Id = reader.GetInt64(reader.GetOrdinal("Id")),
                    ReferenceNumber = reader["ReferenceNumber"]?.ToString(),
                    BankOperationCode = reader["BankOperationCode"]?.ToString(),
                    Currency = reader["Currency"]?.ToString(),
                    OrderingCustomer = reader["OrderingCustomer"]?.ToString(),
                    AccountWithInstitution = reader["AccountWithInstitution"]?.ToString(),
                    Recepient = reader["Recepient"]?.ToString(),
                    RemittanceInformation = reader["RemittanceInformation"]?.ToString(),
                    DetailsOfCharge = reader["DetailsOfCharge"]?.ToString(),

                    // Convert date to a proper DateTime, and InterbankSettled to a decimal type, ready to be saved in the db
                    ValueDate = DateTime.Parse(reader["ValueDate"].ToString()),
                    InterbankSettled = Convert.ToDecimal(reader["InterbankSettled"])
                };

                messages.Add(message);
            }

            Logger.Info("Got {Count} MT103 messages from the database.", messages.Count);

            return messages;
        }

        /// <summary>
        /// Saves a new MT103Message in the database
        /// </summary>
        /// <param name="message">The message to save</param>
        /// <returns>Autogenerated id of the saved message</returns>
        public async Task<long> SaveAsync(MT103Message message)
        {
            using var connection = new SqliteConnection(_connectionString);
            await connection.OpenAsync();

            using var command = connection.CreateCommand();
            command.CommandText = @"
                INSERT INTO MT103Messages(
                    ReferenceNumber,
                    BankOperationCode,
                    ValueDate,
                    Currency,
                    InterbankSettled,
                    OrderingCustomer,
                    AccountWithInstitution,
                    Recepient,
                    RemittanceInformation,
                    DetailsOfCharge 
                )
                VALUES(
                    @ReferenceNumber,
                    @BankOperationCode,
                    @ValueDate,
                    @Currency,
                    @InterbankSettled,
                    @OrderingCustomer,
                    @AccountWithInstitution,
                    @Recepient,
                    @RemittanceInformation,
                    @DetailsOfCharge
                );

                SELECT last_insert_rowid();
            ";

            command.Parameters.AddWithValue("@ReferenceNumber", message.ReferenceNumber);
            command.Parameters.AddWithValue("@BankOperationCode", message.BankOperationCode);
            command.Parameters.AddWithValue("@ValueDate", message.ValueDate);
            command.Parameters.AddWithValue("@Currency", message.Currency);
            command.Parameters.AddWithValue("@InterbankSettled", message.InterbankSettled);
            command.Parameters.AddWithValue("@OrderingCustomer", message.OrderingCustomer);
            command.Parameters.AddWithValue("@AccountWithInstitution", message.AccountWithInstitution);
            command.Parameters.AddWithValue("@Recepient", message.Recepient);
            command.Parameters.AddWithValue("@RemittanceInformation", message.RemittanceInformation);
            command.Parameters.AddWithValue("@DetailsOfCharge", message.DetailsOfCharge);

            var id = (long)(await command.ExecuteScalarAsync());

            Logger.Info("Successfully saved a new MT103 message.");

            return id;
        }
    }
}
